type Info {
  # A unique identifier for the service
  id: ID!
  # A short, human readable name for the service
  name: String!
  # A human readable description for the service
  description: String
  # service readiness level: what functionality you can expect from this current version. Link to further info: https://github.com/maana-io/ServiceReadinessLevels
  srl:Int
}

# ADD YOUR TYPES HERE

type Query {
  info: Info!

  # ADD YOUR QUERIES HERE
}

